"""initial_schema

Revision ID: db91a0ae1c2b
Revises: 
Create Date: 2026-05-27 12:54:23.981800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db91a0ae1c2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('problem', sa.String(), nullable=True),
    sa.Column('process', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('friction_score', sa.Float(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('provider_used', sa.String(), nullable=False),
    sa.Column('memory_schema_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    # ### end Alembic commands ###
