"""add shell to session contexts

Revision ID: fed68f886721
Revises: 123f8dc39e81
Create Date: 2026-05-29 18:51:33.008130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed68f886721'
down_revision: Union[str, Sequence[str], None] = '123f8dc39e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shell', sa.String(), server_default='unknown', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_contexts', schema=None) as batch_op:
        batch_op.drop_column('shell')

    # ### end Alembic commands ###
